<?php
declare(strict_types=1);


use Phinx\Seed\AbstractSeed;

final class OfferTestSeeder extends AbstractSeed
{
    public function run(): void
    {
        $offers = [
            [
                'id' => '1',
                'title' => 'Kleidung tauschen',
                'description' => 'Tausche deine alte Kleidung gegen neue Stücke. Nachhaltig und kostenlos!',
                'category' => 'kleidung',
                'latitude' => 47.5596,
                'longitude' => 7.5886,
                'address' => 'Musterstraße 1, 4051 Basel',
                'status' => 'published',
                'contact_name' => 'Maria Müller',
                'contact_email' => null,
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '2',
                'title' => 'Büchertausch',
                'description' => 'Gemeinsames Tauschen von Büchern.',
                'category' => 'buecher',
                'latitude' => 47.5575,
                'longitude' => 7.592,
                'address' => 'Lesecafé, Hauptstraße 5, 4051 Basel',
                'status' => 'published',
                'contact_name' => 'Thomas Schmidt',
                'contact_email' => 'thomas@buecherfreunde.de',
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '3',
                'title' => 'Spieleabend',
                'description' => 'Kostenloser Spieleabend für alle.',
                'category' => 'aktivitaeten',
                'latitude' => 47.561,
                'longitude' => 7.585,
                'address' => 'Jugendzentrum, Nebenstraße 3, 4051 Basel',
                'status' => 'published',
                'contact_name' => 'Jugendzentrum Team',
                'contact_email' => null,
                'contact_phone' => '+41 61 123 45 67',
                'image_url' => null,
            ],
            [
                'id' => '4',
                'title' => 'Gemüse aus dem Garten',
                'description' => 'Frisches Gemüse aus meinem Garten zu verschenken. Tomaten, Zucchini, Kräuter.',
                'category' => 'essen',
                'latitude' => 47.563,
                'longitude' => 7.58,
                'address' => 'Gartenweg 12, 4052 Basel',
                'status' => 'published',
                'contact_name' => 'Hans Berger',
                'contact_email' => null,
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '5',
                'title' => 'Sprach-Treff für Migranten',
                'description' => 'Kostenlose Deutschkurse und Sprach-Tandems für Migranten.',
                'category' => 'bildung',
                'latitude' => 47.558,
                'longitude' => 7.59,
                'address' => 'Stadtbibliothek Basel, Münsterplatz 2, 4001 Basel',
                'status' => 'published',
                'contact_name' => 'Lisa Weber',
                'contact_email' => 'lisa@stadtbibliothek.ch',
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '6',
                'title' => 'Yoga im Park',
                'description' => 'Kostenlose Yoga-Sessions jeden Samstagmorgen im Stadtpark.',
                'category' => 'sport',
                'latitude' => 47.565,
                'longitude' => 7.575,
                'address' => 'Stadtpark Basel, 4052 Basel',
                'status' => 'published',
                'contact_name' => 'Anna Kim',
                'contact_email' => null,
                'contact_phone' => '+41 61 234 56 78',
                'image_url' => null,
            ],
            [
                'id' => '7',
                'title' => 'Möbel frei abzuholen',
                'description' => 'Sofa, Stuhl und Tisch zu verschenken. Muss selbst abgeholt werden.',
                'category' => 'moebel',
                'latitude' => 47.552,
                'longitude' => 7.595,
                'address' => 'Bahnhofstraße 45, 4051 Basel',
                'status' => 'published',
                'contact_name' => 'Peter Frey',
                'contact_email' => null,
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '8',
                'title' => 'Kochkurs für Anfänger',
                'description' => 'Lerne basische Kochtechniken. Vorkenntnisse nicht nötig.',
                'category' => 'bildung',
                'latitude' => 47.56,
                'longitude' => 7.583,
                'address' => 'Kochschule Pro Spe, Gerbergasse 4, 4001 Basel',
                'status' => 'published',
                'contact_name' => 'Maria Santos',
                'contact_email' => 'maria@kochschule-basel.ch',
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '9',
                'title' => 'Nachbarschafts-Café',
                'description' => 'Offenes Café für alle Nachbarn. Gemütliches Beisammensein.',
                'category' => 'soziales',
                'latitude' => 47.5565,
                'longitude' => 7.5855,
                'address' => 'Nachbarschaftszentrum, Klybeckstraße 1, 4057 Basel',
                'status' => 'published',
                'contact_name' => 'Nachbarschaft Basel',
                'contact_email' => null,
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '10',
                'title' => 'Fahrrad reparatur',
                'description' => 'Kostenlose Fahrrad-Reparatur für alle. Kleine Reparaturen und Wartung.',
                'category' => 'mobilitaet',
                'latitude' => 47.554,
                'longitude' => 7.6,
                'address' => 'Velo-Werkstatt, Freie Straße 22, 4001 Basel',
                'status' => 'published',
                'contact_name' => 'Markus Sutter',
                'contact_email' => 'markus@velowerkstatt.ch',
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '11',
                'title' => 'Kinderhüeti',
                'description' => 'Biete kostenlose Kinderhüeti für parents in der Nachbarschaft.',
                'category' => 'soziales',
                'latitude' => 47.567,
                'longitude' => 7.578,
                'address' => 'Elternzentrum, Margarethenstraße 8, 4053 Basel',
                'status' => 'published',
                'contact_name' => 'Sophie Brunner',
                'contact_email' => null,
                'contact_phone' => '+41 61 345 67 89',
                'image_url' => null,
            ],
            [
                'id' => '12',
                'title' => 'Puzzle-Tausch',
                'description' => 'Tausche deine fertigen Puzzles gegen neue. 1000-2000 Teile.',
                'category' => 'freizeit',
                'latitude' => 47.559,
                'longitude' => 7.5925,
                'address' => 'Spielzeugladen Spielpunkt, Marktplatz 10, 4001 Basel',
                'status' => 'published',
                'contact_name' => 'Claudia Meier',
                'contact_email' => null,
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '13',
                'title' => 'Gitarrenunterricht',
                'description' => 'Kostenloser Gitarrenunterricht für Kinder und Jugendliche.',
                'category' => 'bildung',
                'latitude' => 47.555,
                'longitude' => 7.587,
                'address' => 'Musikschule Kleinbasel,Clarastraße 15, 4058 Basel',
                'status' => 'published',
                'contact_name' => 'Stefan Koch',
                'contact_email' => 'stefan@musikschule-basel.ch',
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '14',
                'title' => 'Haustierfutter zu verschenken',
                'description' => 'Zu viel Katzenfutter gekauft. Haltbarkeitsdatum 2025.',
                'category' => 'tiere',
                'latitude' => 47.562,
                'longitude' => 7.582,
                'address' => 'Rheingasse 8, 4058 Basel',
                'status' => 'published',
                'contact_name' => 'Nina Vogel',
                'contact_email' => null,
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '15',
                'title' => 'Spielnachmittag für Senioren',
                'description' => 'Jeden Dienstag Kartenspiele und Gesellschaftsspiele für Senioren.',
                'category' => 'soziales',
                'latitude' => 47.566,
                'longitude' => 7.57,
                'address' => 'Seniorenzentrum Gundeldingen, Belforterstraße 9, 4054 Basel',
                'status' => 'published',
                'contact_name' => 'René Berger',
                'contact_email' => null,
                'contact_phone' => '+41 61 456 78 90',
                'image_url' => null,
            ],
            [
                'id' => '16',
                'title' => 'PC-Reparatur-Hilfe',
                'description' => 'Helfe bei Computerproblemen. Installation, Virenentfernung, etc.',
                'category' => 'technik',
                'latitude' => 47.551,
                'longitude' => 7.598,
                'address' => 'Café Computer, Steinenvorstadt 5, 4051 Basel',
                'status' => 'published',
                'contact_name' => 'David Schmid',
                'contact_email' => 'david@pc-hilfe-basel.ch',
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '17',
                'title' => 'Backkurs für Kinder',
                'description' => 'Kinder lernen gemeinsam Kuchen und Brötchen backen.',
                'category' => 'bildung',
                'latitude' => 47.564,
                'longitude' => 7.576,
                'address' => 'Familienzentrum, Güterstraße 173, 4052 Basel',
                'status' => 'published',
                'contact_name' => 'Julia Keller',
                'contact_email' => null,
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '18',
                'title' => 'Stricken für Anfänger',
                'description' => 'Lerne Stricken mit Nadeln und Garn. Material wird gestellt.',
                'category' => 'freizeit',
                'latitude' => 47.557,
                'longitude' => 7.58,
                'address' => 'Handarbeitsladen Zwirnerei, Freie Straße 35, 4001 Basel',
                'status' => 'published',
                'contact_name' => 'Elisabeth Roth',
                'contact_email' => null,
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '19',
                'title' => 'Umzugshilfe',
                'description' => 'Helfe bei Umzügen. Knochenarbeit, aber kostenlos.',
                'category' => 'soziales',
                'latitude' => 47.553,
                'longitude' => 7.593,
                'address' => '4051 Basel',
                'status' => 'published',
                'contact_name' => 'Tom Huber',
                'contact_email' => null,
                'contact_phone' => '+41 79 567 89 01',
                'image_url' => null,
            ],
            [
                'id' => '20',
                'title' => 'Gartenarbeit-Hilfe',
                'description' => 'Biete Hilfe bei Gartenarbeiten. Jäten, Giessen, Schneiden.',
                'category' => 'garten',
                'latitude' => 47.568,
                'longitude' => 7.572,
                'address' => '4051 Basel',
                'status' => 'published',
                'contact_name' => 'Franz Müller',
                'contact_email' => null,
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '21',
                'title' => 'Musik-Jam-Session',
                'description' => 'Offene Jam-Session für Musiker. Bring dein Instrument mit.',
                'category' => 'freizeit',
                'latitude' => 47.5555,
                'longitude' => 7.5955,
                'address' => 'Kulturzentrum Halle 7, Klybeckstraße 7, 4057 Basel',
                'status' => 'published',
                'contact_name' => 'Jazz Club Basel',
                'contact_email' => 'info@jazzclub-basel.ch',
                'contact_phone' => null,
                'image_url' => null,
            ],
            [
                'id' => '22',
                'title' => 'Wandergruppe',
                'description' => 'Wöchentliche Wanderungen in und um Basel. Leichte bis mittlere Route.',
                'category' => 'sport',
                'latitude' => 47.57,
                'longitude' => 7.565,
                'address' => 'Basel SBB, Hauptbahnhof, 4051 Basel',
                'status' => 'published',
                'contact_name' => 'Wanderfreunde Basel',
                'contact_email' => null,
                'contact_phone' => '+41 61 567 89 01',
                'image_url' => null,
            ],
            [
                'id' => '23',
                'title' => 'Beratung für Arbeitssuchende',
                'description' => 'Kostenlose Beratung für Arbeitssuchende. Lebensläufe, Vorstellungsgespräche.',
                'category' => 'soziales',
                'latitude' => 47.5595,
                'longitude' => 7.588,
                'address' => 'Rathaus Basel, Marktplatz 1, 4001 Basel',
                'status' => 'published',
                'contact_name' => 'Sozialamt Basel',
                'contact_email' => 'sozialamt@bs.ch',
                'contact_phone' => null,
                'image_url' => null,
            ],
        ];

        $this->table('offers')->insert($offers)->save();
    }
}