import { createFeature, createReducer, on } from '@ngrx/store';
import { AuthActions } from './auth.actions';
import { AuthState, initialState } from './auth.state';

export const authFeature = createFeature({
  name: 'auth',
  reducer: createReducer<AuthState>(
    initialState,
    on(AuthActions.login, (state) => ({
      ...state,
      loading: true,
      errorCode: null,
      fairgateUserExists: null,
      childrenCount: null,
      adultsCount: null,
      salutation: null,
    })),
    on(AuthActions.loginSuccess, (state, { token, userId, group, requiredPasswordReset }) => ({
      ...state,
      token,
      userId,
      group,
      requiredPasswordReset,
      loading: false,
      errorCode: null,
    })),
    on(AuthActions.loginFailure, (state, { errorCode }) => ({
      ...state,
      token: null,
      userId: null,
      group: null,
      requiredPasswordReset: false,
      loading: false,
      errorCode,
      fairgateUserExists: null,
      childrenCount: null,
      adultsCount: null,
      salutation: null,
    })),
    on(AuthActions.registrationLogin, (state) => ({
      ...state,
      registrationLoginLoading: true,
      registrationLoginErrorCode: null,
    })),
    on(AuthActions.registrationLoginSuccess, (state, result) => ({
      ...state,
      token: result.token,
      userId: result.userId,
      group: result.group,
      registrationLoginLoading: false,
      registrationLoginErrorCode: null,
      fairgateUserExists: result.fairgateUserExists,
      childrenCount: result.childrenCount,
      adultsCount: result.adultsCount,
      salutation: result.salutation,
    })),
    on(AuthActions.registrationLoginFailure, (state, { errorCode }) => ({
      ...state,
      token: null,
      userId: null,
      group: null,
      registrationLoginLoading: false,
      registrationLoginErrorCode: errorCode,
      fairgateUserExists: null,
      childrenCount: null,
      adultsCount: null,
      salutation: null,
    })),
    on(AuthActions.passwordChangeSuccess, (state) => ({
      ...state,
      requiredPasswordReset: false,
      passwordChangeLoading: false,
      passwordChangeErrorCode: null,
    })),
    on(AuthActions.passwordChange, (state) => ({
      ...state,
      passwordChangeLoading: true,
      passwordChangeErrorCode: null,
    })),
    on(AuthActions.passwordChangeFailure, (state, { errorCode }) => ({
      ...state,
      passwordChangeLoading: false,
      passwordChangeErrorCode: errorCode,
    })),
    on(AuthActions.logout, () => initialState),
  ),
});

export const {
  name: authFeatureName,
  reducer: authReducer,
  selectAuthState,
  selectToken: selectAuthToken,
  selectUserId: selectAuthUserId,
  selectGroup: selectAuthGroup,
  selectRequiredPasswordReset: selectAuthRequiredPasswordReset,
  selectPasswordChangeLoading: selectAuthPasswordChangeLoading,
  selectPasswordChangeErrorCode: selectAuthPasswordChangeErrorCode,
  selectLoading: selectAuthLoading,
  selectErrorCode: selectAuthErrorCode,
  selectRegistrationLoginLoading: selectAuthRegistrationLoginLoading,
  selectRegistrationLoginErrorCode: selectAuthRegistrationLoginErrorCode,
  selectFairgateUserExists: selectAuthFairgateUserExists,
  selectChildrenCount: selectAuthChildrenCount,
  selectAdultsCount: selectAuthAdultsCount,
  selectSalutation: selectAuthSalutation,
} = authFeature;
