import { createFeature, createReducer, on } from '@ngrx/store';
import { AuthActions } from './auth.actions';
import { SessionActions } from './session.actions';
import { AuthState, initialState } from './auth.state';

export const authFeature = createFeature({
  name: 'auth',
  reducer: createReducer<AuthState>(
    initialState,
    on(AuthActions.login, (state) => ({
      ...state,
      loading: true,
      errorCode: null,
      email: null,
      fairgateUserExists: null,
      childrenCount: null,
      adultsCount: null,
      salutation: null,
    })),
    on(AuthActions.loginSuccess, (state, { userId, group, requiredPasswordReset, email }) => ({
      ...state,
      userId,
      group,
      requiredPasswordReset,
      loading: false,
      errorCode: null,
      email: email ?? state.email,
    })),
    on(AuthActions.loginFailure, (state, { errorCode }) => ({
      ...state,
      userId: null,
      group: null,
      requiredPasswordReset: false,
      loading: false,
      errorCode,
      email: null,
      fairgateUserExists: null,
      childrenCount: null,
      adultsCount: null,
      salutation: null,
    })),
    on(AuthActions.registrationLogin, (state) => ({
      ...state,
      registrationLoginLoading: true,
      registrationLoginErrorCode: null,
    })),
    on(AuthActions.registrationLoginSuccess, (state, result) => ({
      ...state,
      userId: result.userId,
      group: result.group,
      registrationLoginLoading: false,
      registrationLoginErrorCode: null,
      fairgateUserExists: result.fairgateUserExists,
      childrenCount: result.childrenCount,
      adultsCount: result.adultsCount,
      salutation: result.salutation,
    })),
    on(AuthActions.registrationLoginFailure, (state, { errorCode }) => ({
      ...state,
      userId: null,
      group: null,
      registrationLoginLoading: false,
      registrationLoginErrorCode: errorCode,
      fairgateUserExists: null,
      childrenCount: null,
      adultsCount: null,
      salutation: null,
    })),
    on(AuthActions.passwordChangeSuccess, (state) => ({
      ...state,
      requiredPasswordReset: false,
      passwordChangeLoading: false,
      passwordChangeErrorCode: null,
    })),
    on(AuthActions.passwordChange, (state) => ({
      ...state,
      passwordChangeLoading: true,
      passwordChangeErrorCode: null,
    })),
    on(AuthActions.passwordChangeFailure, (state, { errorCode }) => ({
      ...state,
      passwordChangeLoading: false,
      passwordChangeErrorCode: errorCode,
    })),
    on(AuthActions.logoutRequested, () => initialState),
    on(SessionActions.statusLoaded, (state, { expiresAt, secondsRemaining }) => ({
      ...state,
      sessionExpiresAt: expiresAt,
      sessionSecondsRemaining: secondsRemaining,
      sessionWarningVisible: secondsRemaining <= 60,
    })),
    on(SessionActions.refreshRequested, (state) => ({ ...state, sessionRefreshLoading: true })),
    on(SessionActions.refreshSucceeded, (state, { expiresAt, secondsRemaining }) => ({
      ...state,
      sessionExpiresAt: expiresAt,
      sessionSecondsRemaining: secondsRemaining,
      sessionWarningVisible: false,
      sessionRefreshLoading: false,
    })),
    on(SessionActions.refreshFailed, (state) => ({ ...state, sessionRefreshLoading: false })),
    on(SessionActions.countdownStarted, (state) => ({ ...state, sessionWarningVisible: true })),
    on(SessionActions.countdownTick, (state, { secondsRemaining }) => ({ ...state, sessionSecondsRemaining: secondsRemaining })),
    on(SessionActions.countdownStopped, (state) => ({ ...state, sessionWarningVisible: false })),
  ),
});

export const {
  name: authFeatureName,
  reducer: authReducer,
  selectAuthState,
  selectUserId: selectAuthUserId,
  selectGroup: selectAuthGroup,
  selectRequiredPasswordReset: selectAuthRequiredPasswordReset,
  selectPasswordChangeLoading: selectAuthPasswordChangeLoading,
  selectPasswordChangeErrorCode: selectAuthPasswordChangeErrorCode,
  selectLoading: selectAuthLoading,
  selectErrorCode: selectAuthErrorCode,
  selectRegistrationLoginLoading: selectAuthRegistrationLoginLoading,
  selectRegistrationLoginErrorCode: selectAuthRegistrationLoginErrorCode,
  selectFairgateUserExists: selectAuthFairgateUserExists,
  selectChildrenCount: selectAuthChildrenCount,
  selectAdultsCount: selectAuthAdultsCount,
  selectSalutation: selectAuthSalutation,
  selectSessionExpiresAt: selectAuthSessionExpiresAt,
  selectSessionSecondsRemaining: selectAuthSessionSecondsRemaining,
  selectSessionWarningVisible: selectAuthSessionWarningVisible,
  selectSessionRefreshLoading: selectAuthSessionRefreshLoading,
  selectEmail: selectAuthEmail,
} = authFeature;
